import pandas as pd
import gspread
from google.oauth2.service_account import Credentials
from datetime import datetime

"""
Google Sheets Uploader for Alumni Feedback

This script uploads the analyzed alumni feedback from the Excel file
to Google Sheets automatically.

Prerequisites:
1. Install required packages:
   pip install gspread google-auth google-auth-oauthlib google-auth-httplib2

2. Set up Google Service Account:
   - Go to https://console.cloud.google.com/
   - Create a new project or select existing
   - Enable Google Sheets API
   - Create Service Account credentials
   - Download JSON key file
   - Save it as 'credentials/service-account.json'

3. Share your Google Sheet with the service account email
   (found in the JSON file)
"""

# Configuration
CREDENTIALS_FILE = "credentials/service-account.json"
EXCEL_FILE = "Alumni_Feedback_Report_Filtered.xlsx"  # The file generated by data_processor_with_filter.py

def upload_to_sheets(spreadsheet_url, worksheet_name="Sheet1"):
    """
    Upload analyzed alumni feedback to Google Sheets

    Args:
        spreadsheet_url: Full URL of your Google Spreadsheet
        worksheet_name: Name of the worksheet tab (default: "Sheet1")
    """

    print("="*80)
    print("GOOGLE SHEETS UPLOADER")
    print("="*80)

    # 1. Load the analyzed Excel file
    print(f"\n1. Loading data from {EXCEL_FILE}...")
    try:
        df = pd.read_excel(EXCEL_FILE)
        print(f"   ✓ Loaded {len(df)} rows")
    except FileNotFoundError:
        print(f"   ✗ Error: {EXCEL_FILE} not found.")
        print(f"   Run 'python3 data_processor_with_filter.py' first to generate the report.")
        return

    # 2. Authenticate with Google Sheets
    print(f"\n2. Authenticating with Google Sheets...")
    try:
        scopes = [
            'https://www.googleapis.com/auth/spreadsheets',
            'https://www.googleapis.com/auth/drive'
        ]
        creds = Credentials.from_service_account_file(CREDENTIALS_FILE, scopes=scopes)
        client = gspread.authorize(creds)
        print("   ✓ Authentication successful")
    except FileNotFoundError:
        print(f"   ✗ Error: {CREDENTIALS_FILE} not found.")
        print("   Follow the setup instructions in the script comments.")
        return
    except Exception as e:
        print(f"   ✗ Authentication error: {e}")
        return

    # 3. Open the spreadsheet
    print(f"\n3. Opening spreadsheet...")
    try:
        sheet = client.open_by_url(spreadsheet_url)
        worksheet = sheet.worksheet(worksheet_name)
        print(f"   ✓ Opened '{sheet.title}' - '{worksheet_name}'")
    except gspread.exceptions.SpreadsheetNotFound:
        print("   ✗ Error: Spreadsheet not found.")
        print("   Make sure you've shared the sheet with the service account email.")
        return
    except gspread.exceptions.WorksheetNotFound:
        print(f"   ✗ Error: Worksheet '{worksheet_name}' not found.")
        print(f"   Available worksheets: {[ws.title for ws in sheet.worksheets()]}")
        return
    except Exception as e:
        print(f"   ✗ Error opening spreadsheet: {e}")
        return

    # 4. Prepare data for upload
    print(f"\n4. Preparing data...")

    # Convert DataFrame to list of lists for Google Sheets
    # First row = headers, then data rows
    headers = df.columns.tolist()
    data_rows = df.values.tolist()

    # Convert any NaN/None values to empty strings
    data_rows = [[str(cell) if pd.notna(cell) else "" for cell in row] for row in data_rows]

    print(f"   ✓ Prepared {len(data_rows)} rows with {len(headers)} columns")

    # 5. Upload to Google Sheets
    print(f"\n5. Uploading to Google Sheets...")
    try:
        # Clear existing content (optional - comment out if you want to append)
        worksheet.clear()

        # Update with headers + data
        all_data = [headers] + data_rows
        worksheet.update('A1', all_data)

        print(f"   ✓ Successfully uploaded {len(data_rows)} rows to Google Sheets!")
        print(f"\n   View your sheet: {spreadsheet_url}")

    except Exception as e:
        print(f"   ✗ Upload error: {e}")
        return

    # 6. Format the sheet (optional)
    print(f"\n6. Formatting sheet...")
    try:
        # Make header row bold
        worksheet.format('A1:N1', {
            "textFormat": {"bold": True},
            "backgroundColor": {"red": 0.9, "green": 0.9, "blue": 0.9}
        })

        # Freeze header row
        worksheet.freeze(rows=1)

        print(f"   ✓ Formatting applied")
    except Exception as e:
        print(f"   ⚠ Formatting warning: {e}")

    print("\n" + "="*80)
    print("UPLOAD COMPLETE!")
    print("="*80)

def get_service_account_email():
    """Helper function to display the service account email"""
    try:
        import json
        with open(CREDENTIALS_FILE, 'r') as f:
            creds = json.load(f)
            email = creds.get('client_email', 'NOT FOUND')
            print("\n" + "="*80)
            print("SERVICE ACCOUNT EMAIL")
            print("="*80)
            print(f"\nShare your Google Sheet with this email (Editor permissions):")
            print(f"\n   {email}\n")
            print("="*80)
    except FileNotFoundError:
        print(f"\n✗ Error: {CREDENTIALS_FILE} not found.")
        print("Set up your service account first (see script comments).")
    except Exception as e:
        print(f"Error reading credentials: {e}")

if __name__ == "__main__":
    import sys

    print("\n" + "="*80)
    print("ALUMNI FEEDBACK → GOOGLE SHEETS UPLOADER")
    print("="*80)

    # Check if user provided spreadsheet URL
    if len(sys.argv) < 2:
        print("\nUsage:")
        print("   python3 sheets_uploader.py YOUR_SPREADSHEET_URL")
        print("\nExample:")
        print("   python3 sheets_uploader.py https://docs.google.com/spreadsheets/d/ABC123.../edit")
        print("\nOr to see your service account email:")
        print("   python3 sheets_uploader.py --show-email")
        print("\n" + "="*80)
        sys.exit(1)

    # Show service account email if requested
    if sys.argv[1] == "--show-email":
        get_service_account_email()
        sys.exit(0)

    # Upload to sheets
    spreadsheet_url = sys.argv[1]
    worksheet_name = sys.argv[2] if len(sys.argv) > 2 else "Sheet1"

    upload_to_sheets(spreadsheet_url, worksheet_name)
